### ISSUE TITLE
Select languages & frameworks

### ISSUE THREAD

**Issue by gregkrsak** [snohomishaletrail/website#1]
Before work begins, let's lock down what languages and frameworks we'll be using.

@kamon-harrell please do some basic research and come up with a list of technologies you'd like to use. You can discuss them with me here, in this issue.

**Comment by kamon-harrell** [comment]
@gregkrsak This project should be pretty easy to handle with the Foundation front end framework https://foundation.zurb.com/ I have used this before, and since we don't need to be doing anything super extravagent, I think a solution like this will give us the ability to get something up quickly and reduce complexity.  If you take a peek at their showcase https://zurb.com/responsive you can see it's been used by a number of high profile brands. It's also responsive, and will cut down on time needed to hand write code for a good number of things, as they have modules that just need to be installed to work, and modified to fit our use case. This operates with mostly JS, HTML, and CSS. Let me know how you feel about it!

**Comment by kamon-harrell** [comment]
I don't believe there is. I'm under the impression foundation and its dependencies just need to be installed in whatever directory the website is being served from. We could use a CMS, but im pretty sure we can also use it as a standalone. Here's an excerpt from their FAQ page,

Can I use Foundation with [insert CMS of choice here]?
The short answer: yes. You can use it with any CMS. Foundation is basically CSS/SCSS, JavaScript and markup structure that can be used on pretty much any project. Figuring out how to integrate it into whatever system you choose is up to you, we can't be experts at everything :) but you can check out the Resources page to see if someone has already done the legwork!

**Comment by gregkrsak** [comment]
Ok, let's get started. Double check #2 and close these out if there is nothing else with either of them.
